### PR TITLE
Add 'json_data' option to force data JSONification

### PR DESCRIPTION
**Pull request by hbredin**
```
my_api = tortilla.wrap('http://my.api.com/', json_data=True)
```

will make sure that when `data` is sent to the API, it is always JSONify before being sent to `request`.
It also adds the corresponding header `{'Content-Type': 'application/json'}`.

This kind of options could be very useful for JSON-only APIs.

### CODE REVIEW

**Comment by hbredin** [comment]
Any news on the integration of redodo/formats into tortilla?
I am willing to beta test if needed...

**Comment by redodo** [comment]
Of course. I completely forgot about this.

It's close to being done. The formats library needs to get out of alpha and then I will push the changes to tortilla.

I will first probably submit a pre-release of tortilla with the new changes. Which could then be installed with the `--pre` parameter using pip.

Thanks for reminding! :+1:

**Comment by redodo** [comment]
I've pushed out a pre-release which contains the new formats feature. I'll document this in detail later but the basics are as follows:

```python
import tortilla
import myformat

tortilla.formats.register('myformat', myformat.parser, myformat.composer,
                          content_type='application/myformat')

example = tortilla.wrap('https://api.example.org')
# this sends a 'Content-Type' header when not set already
example.endpoint.get(format='myformat')
```

The JSON and YAML formats are registered by default when installed.

**Comment by hbredin** [comment]
Thanks. 

I initially thought that the JSON `data` sent by `PUT`or `POST` requests would automagically be processed by the format `composer` (using your terminology above) before being sent.
It does not seem to be the case and I still need to `json.dumps` my `data` before sending it.

Also, I need to repeat `format='json'` for every call to the API while it could be automagically be added if the API is initialized with this keyword.

Am I missing something?

**Comment by redodo** [comment]
> I initially thought that the `JSON` data sent by `PUT` or `POST` requests would automagically be processed by the format `composer`

That is a good point. I will include this in the next release.

> Also, I need to repeat `format='json'` for every call to the API while it could be automagically be added if the API is initialized with this keyword.

The latest commits include a `format` argument in the initializer of `Wrap`. I think it's not included in the release on PIP.

This would be used like so:

```python
example = tortilla.wrap('https://api.example.org', format='json')
```

**Comment by hbredin** [comment]
OK. Great! I'll wait for the next pip-installable release then :)
Thank you very much for this library!

**Pull request closed without merging**
